// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.5.2_bb1131dfba9a396081eee6cbdf8e8b9b/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mdc@0.22.2_magic-string@1.1.0_magicast@0.5.4_oxc-parser@0.139.0_rolldown@1.2.1__e2d56cf3c7ee8402e0a681212ec49164/node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.3.1_magic-string@0.30.21_magicast@0.5.4_oxc-parser@0.139.0_rolldown@1.2.1__9e48756d4854b53aa221bd18a74dc42c/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_content/content/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.2_@oxc-project+types@0.142.0_@valibot+to-json-schema@1.7.1_valibot@1_403b7ecb83f3767cc7a0a0068e5faeb0/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.2_@oxc-project+types@0.142.0_@valibot+to-json-schema@1.7.1_valibot@1_403b7ecb83f3767cc7a0a0068e5faeb0/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/content/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.2_@oxc-project+types@0.142.0_@valibot+to-json-schema@1.7.1_valibot@1_403b7ecb83f3767cc7a0a0068e5faeb0/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.15.2_@oxc-project+types@0.142.0_@valibot+to-json-schema@1.7.1_valibot@1_403b7ecb83f3767cc7a0a0068e5faeb0/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}