// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const parseMarkdown: typeof import('../../node_modules/.pnpm/@nuxtjs+mdc@0.22.2_magic-string@1.1.0_magicast@0.5.4_oxc-parser@0.139.0_rolldown@1.2.1__e2d56cf3c7ee8402e0a681212ec49164/node_modules/@nuxtjs/mdc/dist/runtime/parser').parseMarkdown
  const stringifyMarkdown: typeof import('../../node_modules/.pnpm/@nuxtjs+mdc@0.22.2_magic-string@1.1.0_magicast@0.5.4_oxc-parser@0.139.0_rolldown@1.2.1__e2d56cf3c7ee8402e0a681212ec49164/node_modules/@nuxtjs/mdc/dist/runtime/stringify').stringifyMarkdown
}